package main

import (
	"os"
	"log"
	"fmt"
	"net/http"
	"github.com/asticode/go-astilectron"
	"io"
	"strings"
)

/*func Disembed(src string) ([]byte, error) {
	if src == "a" {
		return nil, nil
	} else if src == "e" {
		return nil, nil
	} else {
		return nil, errors.New("Wrong argument!")
	}
}*/

func getElectronPath(os, arch string) string {
	// Get OS name
	var o string
	switch strings.ToLower(os) {
	case "darwin":
		o = "darwin"
	case "linux":
		o = "linux"
	case "windows":
		o = "win32"
	}

	// Get arch name
	var a = "ia32"
	if strings.ToLower(arch) == "amd64" || o == "darwin" {
		a = "x64"
	}

	// Set url
	return fmt.Sprintf("https://github.com/electron/electron/releases/download/v%s/electron-v%s-%s-%s.zip", astilectron.VersionElectron, astilectron.VersionElectron, o, a)
}

type W struct{
	io.Writer
}

func(w *W) Write(p []byte) (n int, err error) {
	for _, b := range p {
		_, err = fmt.Fprintf(w.Writer, "\\x%02x", b)
	}
	n = len(p)
	return
}

func main() {
	for _, o := range []string{"linux", "darwin", "windows"} {
		for _, a := range []string{"amd64", "386"} {
			if o == "darwin" && a == "386" {
				continue
			}
			file, err := os.Create(fmt.Sprintf("astilectron_vendor_%s_%s.go", o, a))
			defer file.Close()
			if err != nil {
				log.Fatal(err)
			}
			file.WriteString("// Generated by go-astilectron-bindata\n\n")
			file.WriteString("// +build " + o + "\n")
			file.WriteString("// +build " + a + "\n")
			file.WriteString(`
package main
import "errors"
`)
			file.WriteString(`func Disembed(src string) ([]byte, error) {
	if src == "a" {
		return []byte("`)
			resp, err := http.Get(fmt.Sprintf("https://github.com/asticode/astilectron/archive/v%s.zip", astilectron.VersionAstilectron))
			if err != nil {
				log.Fatal(err)
			}
			_, err = io.Copy(&W{Writer: file}, resp.Body)
			if err != nil {
				log.Fatal(err)
			}
			file.WriteString(`"), nil
	} else if src == "e" {
		return []byte("`)
			resp, err = http.Get(getElectronPath(o, a))
			if err != nil {
				log.Fatal(err)
			}
			_, err = io.Copy(&W{Writer: file}, resp.Body)
			if err != nil {
				log.Fatal(err)
			}
			file.WriteString(`"), nil
	} else {
		return nil, errors.New("Wrong argument!")
	}
}`)
		}
	}
}
